/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.sisloj;

import br.senai.sc.sisloj.views.CadastroCliente;
import br.senai.sc.sisloj.views.PainelAmarelo;
import br.senai.sc.sisloj.views.PainelRosa;
import br.senai.sc.sisloj.views.TelaPadrao;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class SisLojFrame extends javax.swing.JFrame {

    /**
     * Creates new form SisLojFrame
     */
    public SisLojFrame() {
        initComponents();
        
        TelaPadrao TP = new TelaPadrao();
        PainelRosa pRosa = new PainelRosa();
        PainelAmarelo pAmarelo = new PainelAmarelo();
        CadastroCliente cadDeCli = new CadastroCliente();
        
        painelPrincipal.add(TP, "PainelPrincip");
        painelPrincipal.add(pRosa, "painelRosa");
        painelPrincipal.add(pAmarelo, "painelAmarelo");   
        painelPrincipal.add(cadDeCli, "CadastroDosClientes");
        
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        BarraDeMenu = new javax.swing.JMenuBar();
        MenCliente = new javax.swing.JMenu();
        menCadastrarCLiente = new javax.swing.JMenuItem();
        menListarCliente = new javax.swing.JMenuItem();
        MenProduto = new javax.swing.JMenu();
        menCadastrarProduto = new javax.swing.JMenuItem();
        menListarProdutos = new javax.swing.JMenuItem();
        menProdutosEmFalta = new javax.swing.JMenuItem();
        MenPainelColorido = new javax.swing.JMenu();
        PainelAmarelo = new javax.swing.JMenuItem();
        PaineRosa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));

        painelPrincipal.setPreferredSize(new java.awt.Dimension(500, 500));
        painelPrincipal.setLayout(new java.awt.CardLayout());

        MenCliente.setText("Cliente");

        menCadastrarCLiente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menCadastrarCLiente.setText("Cadastrar Cliente");
        menCadastrarCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastrarCLienteActionPerformed(evt);
            }
        });
        MenCliente.add(menCadastrarCLiente);

        menListarCliente.setText("Listar Clientes");
        MenCliente.add(menListarCliente);

        BarraDeMenu.add(MenCliente);

        MenProduto.setText("Produto");

        menCadastrarProduto.setText("Cadastrar Produto");
        MenProduto.add(menCadastrarProduto);

        menListarProdutos.setText("Listar Produtos");
        MenProduto.add(menListarProdutos);

        menProdutosEmFalta.setText("Prudos em Falta");
        MenProduto.add(menProdutosEmFalta);

        BarraDeMenu.add(MenProduto);

        MenPainelColorido.setText("Paineis Coloridos");

        PainelAmarelo.setText("PainelAmarelo");
        PainelAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PainelAmareloActionPerformed(evt);
            }
        });
        MenPainelColorido.add(PainelAmarelo);

        PaineRosa.setText("PainelRosa");
        PaineRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaineRosaActionPerformed(evt);
            }
        });
        MenPainelColorido.add(PaineRosa);

        BarraDeMenu.add(MenPainelColorido);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menCadastrarCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastrarCLienteActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "CadastroDosClientes");      
    }//GEN-LAST:event_menCadastrarCLienteActionPerformed

    private void PainelAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PainelAmareloActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "painelAmarelo");
    }//GEN-LAST:event_PainelAmareloActionPerformed

    private void PaineRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaineRosaActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "painelRosa");
    }//GEN-LAST:event_PaineRosaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SisLojFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JMenu MenCliente;
    private javax.swing.JMenu MenPainelColorido;
    private javax.swing.JMenu MenProduto;
    private javax.swing.JMenuItem PaineRosa;
    private javax.swing.JMenuItem PainelAmarelo;
    private javax.swing.JMenuItem menCadastrarCLiente;
    private javax.swing.JMenuItem menCadastrarProduto;
    private javax.swing.JMenuItem menListarCliente;
    private javax.swing.JMenuItem menListarProdutos;
    private javax.swing.JMenuItem menProdutosEmFalta;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
